export const FO_STOCKS = [
  { symbol: "RELIANCE.NS", name: "Reliance Industries Limited" },
  { symbol: "TCS.NS", name: "Tata Consultancy Services Limited" },
  { symbol: "HDFCBANK.NS", name: "HDFC Bank Limited" },
  { symbol: "ICICIBANK.NS", name: "ICICI Bank Limited" },
  { symbol: "INFY.NS", name: "Infosys Limited" },
  { symbol: "ITC.NS", name: "ITC Limited" },
  { symbol: "SBIN.NS", name: "State Bank of India" },
  { symbol: "BHARTIARTL.NS", name: "Bharti Airtel Limited" },
  { symbol: "KOTAKBANK.NS", name: "Kotak Mahindra Bank Limited" },
  { symbol: "L&TFH.NS", name: "L&T Finance Holdings Limited" },
  { symbol: "AXISBANK.NS", name: "Axis Bank Limited" },
  { symbol: "BAJFINANCE.NS", name: "Bajaj Finance Limited" },
  { symbol: "LT.NS", name: "Larsen & Toubro Limited" },
  { symbol: "HINDUNILVR.NS", name: "Hindustan Unilever Limited" },
  { symbol: "MARUTI.NS", name: "Maruti Suzuki India Limited" },
  { symbol: "SUNPHARMA.NS", name: "Sun Pharmaceutical Industries Limited" },
  { symbol: "TITAN.NS", name: "Titan Company Limited" },
  { symbol: "ULTRACEMCO.NS", name: "UltraTech Cement Limited" },
  { symbol: "ASIANPAINT.NS", name: "Asian Paints Limited" },
  { symbol: "HCLTECH.NS", name: "HCL Technologies Limited" },
  { symbol: "NTPC.NS", name: "NTPC Limited" },
  { symbol: "TATASTEEL.NS", name: "Tata Steel Limited" },
  { symbol: "ADANIENT.NS", name: "Adani Enterprises Limited" },
  { symbol: "BAJAJFINSV.NS", name: "Bajaj Finserv Limited" },
  { symbol: "POWERGRID.NS", name: "Power Grid Corporation of India Limited" },
  { symbol: "M&M.NS", name: "Mahindra & Mahindra Limited" },
  { symbol: "ONGC.NS", name: "Oil & Natural Gas Corporation Limited" },
  { symbol: "JSWSTEEL.NS", name: "JSW Steel Limited" },
  { symbol: "HINDALCO.NS", name: "Hindalco Industries Limited" },
  { symbol: "TATAMOTORS.NS", name: "Tata Motors Limited" },
  { symbol: "WIPRO.NS", name: "Wipro Limited" },
  { symbol: "NESTLEIND.NS", name: "Nestle India Limited" },
  { symbol: "SBILIFE.NS", name: "SBI Life Insurance Company Limited" },
  { symbol: "COALINDIA.NS", name: "Coal India Limited" },
  { symbol: "GRASIM.NS", name: "Grasim Industries Limited" },
  { symbol: "TECHM.NS", name: "Tech Mahindra Limited" },
  { symbol: "BAJAJ-AUTO.NS", name: "Bajaj Auto Limited" },
  { symbol: "HDFCLIFE.NS", name: "HDFC Life Insurance Company Limited" },
  { symbol: "INDUSINDBK.NS", name: "IndusInd Bank Limited" },
  { symbol: "DRREDDY.NS", name: "Dr. Reddy's Laboratories Limited" },
  { symbol: "BRITANNIA.NS", name: "Britannia Industries Limited" },
  { symbol: "APOLLOHOSP.NS", name: "Apollo Hospitals Enterprise Limited" },
  { symbol: "CIPLA.NS", name: "Cipla Limited" },
  { symbol: "DIVISLAB.NS", name: "Divi's Laboratories Limited" },
  { symbol: "EICHERMOT.NS", name: "Eicher Motors Limited" },
  { symbol: "TATACONSUM.NS", name: "Tata Consumer Products Limited" },
  { symbol: "BPCL.NS", name: "Bharat Petroleum Corporation Limited" },
  { symbol: "HEROMOTOCO.NS", name: "Hero MotoCorp Limited" },
  { symbol: "UPL.NS", name: "UPL Limited" },
  { symbol: "AARTIIND.NS", name: "Aarti Industries Limited" },
  { symbol: "ABB.NS", name: "ABB India Limited" },
  { symbol: "ABBOTINDIA.NS", name: "Abbott India Limited" },
  { symbol: "ABCAPITAL.NS", name: "Aditya Birla Capital Limited" },
  { symbol: "ABFRL.NS", name: "Aditya Birla Fashion and Retail Limited" },
  { symbol: "ACC.NS", name: "ACC Limited" },
  { symbol: "ADANIPORTS.NS", name: "Adani Ports and Special Economic Zone Limited" },
  { symbol: "ALKEM.NS", name: "Alkem Laboratories Limited" },
  { symbol: "AMBUJACEM.NS", name: "Ambuja Cements Limited" },
  { symbol: "APOLLOTYRE.NS", name: "Apollo Tyres Limited" },
  { symbol: "ASHOKLEY.NS", name: "Ashok Leyland Limited" },
  { symbol: "ASTRAL.NS", name: "Astral Limited" },
  { symbol: "ATUL.NS", name: "Atul Limited" },
  { symbol: "AUBANK.NS", name: "AU Small Finance Bank Limited" },
  { symbol: "AUROPHARMA.NS", name: "Aurobindo Pharma Limited" },
  { symbol: "BALRAMCHIN.NS", name: "Balrampur Chini Mills Limited" },
  { symbol: "BANDHANBNK.NS", name: "Bandhan Bank Limited" },
  { symbol: "BANKBARODA.NS", name: "Bank of Baroda" },
  { symbol: "BATAINDIA.NS", name: "Bata India Limited" },
  { symbol: "BEL.NS", name: "ABB India Limited" },
  { symbol: "BERGEPAINT.NS", name: "Berger Paints (I) Limited" },
  { symbol: "BHARATFORG.NS", name: "Bharat Forge Limited" },
  { symbol: "BHEL.NS", name: "Bharat Electronics Limited" },
  { symbol: "BIOCON.NS", name: "Biocon Limited" },
  { symbol: "BOSCHLTD.NS", name: "Bosch Limited" },
  { symbol: "CANBK.NS", name: "Canara Bank" },
  { symbol: "CHAMBLFERT.NS", name: "Chambal Fertilizers & Chemicals Limited" },
  { symbol: "CHOLAFIN.NS", name: "Cholamandalam Investment and Finance Company Limited" },
  { symbol: "COFORGE.NS", name: "Coforge Limited" },
  { symbol: "CONCOR.NS", name: "Container Corporation of India Limited" },
  { symbol: "COROMANDEL.NS", name: "Coromandel International Limited" },
  { symbol: "CROMPTON.NS", name: "Crompton Greaves Consumer Electricals Limited" },
  { symbol: "CUB.NS", name: "AU Small Finance Bank Limited" },
  { symbol: "CUMMINSIND.NS", name: "Crompton Greaves Consumer Electricals Limited" },
  { symbol: "DABUR.NS", name: "Dabur India Limited" },
  { symbol: "DALBHARAT.NS", name: "Dalmia Bharat Limited" },
  { symbol: "DEEPAKNTR.NS", name: "Deepak Nitrite Limited" },
  { symbol: "DELTACORP.NS", name: "Delta Corp Limited" },
  { symbol: "DIXON.NS", name: "Dixon Technologies (India) Limited" },
  { symbol: "ESCORTS.NS", name: "Escorts Kubota Limited" },
  { symbol: "EXIDEIND.NS", name: "Exide Industries Limited" },
  { symbol: "FEDERALBNK.NS", name: "The Federal Bank  Limited" },
  { symbol: "GAIL.NS", name: "GAIL (India) Limited" },
  { symbol: "GLENMARK.NS", name: "Glenmark Pharmaceuticals Limited" },
  { symbol: "GMRINFRA.NS", name: "GMR Airports Infrastructure Limited" },
  { symbol: "GNFC.NS", name: "Gujarat Narmada Valley Fertilizers and Chemicals Limited" },
  { symbol: "GODREJCP.NS", name: "Godrej Consumer Products Limited" },
  { symbol: "GODREJPROP.NS", name: "Godrej Properties Limited" },
  { symbol: "GRANULES.NS", name: "Granules India Limited" },
  { symbol: "GUJGASLTD.NS", name: "Gujarat Gas Limited" },
  { symbol: "HAL.NS", name: "Hindustan Aeronautics Limited" },
  { symbol: "HAVELLS.NS", name: "Havells India Limited" },
  { symbol: "HDFCAMC.NS", name: "HDFC Asset Management Company Limited" },
  { symbol: "ICICIGI.NS", name: "ICICI Lombard General Insurance Company Limited" },
  { symbol: "ICICIPRULI.NS", name: "ICICI Prudential Life Insurance Company Limited" },
  { symbol: "IDEA.NS", name: "Vodafone Idea Limited" },
  { symbol: "IDFCFIRSTB.NS", name: "IDFC First Bank Limited" },
  { symbol: "IEX.NS", name: "Indian Energy Exchange Limited" },
  { symbol: "IGL.NS", name: "Indraprastha Gas Limited" },
  { symbol: "INDHOTEL.NS", name: "The Indian Hotels Company Limited" },
  { symbol: "INDIACEM.NS", name: "The India Cements Limited" },
  { symbol: "INDIAMART.NS", name: "IndiaMART InterMESH Limited" },
  { symbol: "INDIGO.NS", name: "InterGlobe Aviation Limited" },
  { symbol: "INDUSTOWER.NS", name: "Indus Towers Limited" },
  { symbol: "IPCALAB.NS", name: "IPCA Laboratories Limited" },
  { symbol: "IRCTC.NS", name: "Indian Railway Catering And Tourism Corporation Limited" }
];
